name: 'Get The Default Branch'
description: 'Get the default branch for this repository'
branding:
  icon: 'git-branch'
  color: 'green'
outputs:
  default_branch:
    description: "The default branch name"
runs:
  using: 'composite'
  steps:
    - id: default-branch-name
      shell: bash
      run: |
        default_branch=$(curl -s https://api.github.com/repos/${{ github.repository }} -H "Authorization: bearer ${{ github.token }}" | jq -r .default_branch)
        echo "default_branch=$default_branch" >> $GITHUB_OUTPUT
