on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Make sure the action works
    steps:
      - uses: actions/checkout@v2
      - id: default-branch
        uses: scottmmjackson/get-the-default-branch-action@next
      - if: ${{ steps.default-branch.outputs.default_branch == 'main' }}
        run: echo "Success! The default branch is in fact 'main'!"
      - if: ${{ steps.default-branch.outputs.default_branch != 'main' }}
        run: |
          echo "Failure: the default branch is ${{ steps.default-branch.outputs.default-branch }} and not main"
          exit 1

